version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=arushi0404patni_Demo-java-app -Dsonar.organization=arushi0404patni-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=83060cd46ced0992426f04bd172d7ae0f80f634e
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-petclinic-2.1.0.jar